# Site settings
title: immsrini 
description: 
favicon: assets/img/favicon.ico
baseurl: ""
url: ""
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Mukundhan Srinivasan
  title: 
  address: 
  email: msrini@marketlearning.io
  link: http://forkmsrini.github.io
  weibo:
  github: forkmsrini
  linkedin: mukundhansrinivasan
  twitter: immsrini
  gavatar: ~/assets/img/jetpacktocat.png
  workHistory:
    - work1:
      company: Nanyang Technological University
      location: Singapore
      title: Researcher
      started: 2015
      duration: (2015 - Today)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: TheThingsCloud | Market Learning Labs | Latent Machines | Forget2Remember
      location: Bangalore, India
      title: Founding & Technical Roles
      started: 2015
      duration: (December 2014 - Today)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Robert Bosch Center of Cyberphysical Systems (RBCCPS), Indian Institute of Science
      location: Bangalore, India
      title: Research Assistant
      started: 2015
      duration: (July 2015 - November 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work4:
      company: Medical Intelligence and Language Engineering Lab (MILE), Indian Institute Of Science
      location: Bangalore, India
      title: Research Assistant
      started: 2013
      duration: (June 2013 - March 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work5:
      company: IEEE
      location: Bangalore, India
      title: Volunteer
      started: 2010
      duration: (2010 - Today)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Stanford Graduate Business School
      degree: Ignite Scholar
      major: Business Management
      started: 2015
      duration: (2016)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: Anna University
      degree: Bachelor
      major: Electronics and Communication Engineering
      started: 2009
      duration: (August 2009 - May 2013)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education3:
      organization: NIIT
      degree: Associate
      major: Software Engineering
      started: 2009
      duration: (July 2009 - March 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: English
      proficiency: Fluent
    - language2:
      name: Tamil
      proficiency: Native
    - language3:
      name: Kannada
      proficiency: Native
    - language4:
      name: Sanskrit
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Python
      percentage: 90%
    - skill2:
      name: C/C++
      percentage: 85%
    - skill3:
      name: JavaScript
      percentage: 60%
    - skill4:
      name: Numpy, Scipy, Matplotlib, Sklearn
      percentage: 85%
    - skill5:
      name: HTML, CSS, (MEAN) stack
      percentage: 70%
    - skill6:
      name: LaTeX and MS Office Suite
      percentage: 94%

